# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikout <- function(sigma, u, ncauses, causes, alpha, dalpha, beta, gamma) {
    .Call('mcif_loglikout', PACKAGE = 'mcif', sigma, u, ncauses, causes, alpha, dalpha, beta, gamma)
}

Dloglikout <- function(sigma, u, ncauses, causes, alpha, dalpha, beta, gamma) {
    .Call('mcif_Dloglikout', PACKAGE = 'mcif', sigma, u, ncauses, causes, alpha, dalpha, beta, gamma)
}

D2loglikout <- function(sigma, u, ncauses, causes, alpha, dalpha, beta, gamma) {
    .Call('mcif_D2loglikout', PACKAGE = 'mcif', sigma, u, ncauses, causes, alpha, dalpha, beta, gamma)
}

loglik <- function(sigma, ncauses, causes, alpha, dalpha, beta, gamma, eb0, nq = 1L, stepsize = 0.7, iter = 20L, debug = FALSE) {
    .Call('mcif_loglik', PACKAGE = 'mcif', sigma, ncauses, causes, alpha, dalpha, beta, gamma, eb0, nq, stepsize, iter, debug)
}

loglikold <- function(y, b, sigma, alph, dalph, tau, eb0, nq = 1L, stepsize = 0.7, iter = 20L, debug = FALSE) {
    .Call('mcif_loglikold', PACKAGE = 'mcif', y, b, sigma, alph, dalph, tau, eb0, nq, stepsize, iter, debug)
}

EB <- function(y, b, sigma, alph, dalph, tau, stepsize = 0.7, iter = 20L, debug = FALSE) {
    .Call('mcif_EB', PACKAGE = 'mcif', y, b, sigma, alph, dalph, tau, stepsize, iter, debug)
}

logliktest <- function(y, b, u, sigma, alph, dalph, tau) {
    .Call('mcif_logliktest', PACKAGE = 'mcif', y, b, u, sigma, alph, dalph, tau)
}

Dlogliktest <- function(y, b, u, sigma, alph, dalph, tau) {
    .Call('mcif_Dlogliktest', PACKAGE = 'mcif', y, b, u, sigma, alph, dalph, tau)
}

pn <- function(y, mu, sigma) {
    .Call('mcif_pn', PACKAGE = 'mcif', y, mu, sigma)
}

test <- function(ncauses, causes, alpha, dalpha, beta, gamma) {
    .Call('mcif_test', PACKAGE = 'mcif', ncauses, causes, alpha, dalpha, beta, gamma)
}

